---

- name: Install Poetry
  become: yes
  become_user: '{{ python_deploy__user }}'
  when: python_deploy__use_poetry
  block:
  - name: Download Poetry installer
    get_url:
      url: '{{ python_deploy__poetry_installer_url }}'
      dest: '{{ python_deploy__path_root }}/get-poetry.py'
      mode: '0755'

  - name: Ensure latest Poetry version is installed
    shell: 'python {{ python_deploy__path_root }}/get-poetry.py -y --no-modify-path'
    register: result
    environment:
      - POETRY_HOME: '{{ python_deploy__poetry_install_path }}'
    changed_when: '"Latest version already installed" not in result.stdout'
    when: python_deploy__poetry_version == 'latest'

  - name: 'Ensure Poetry version {{ python_deploy__poetry_version }} is installed'
    shell: '{{ python_deploy__python }} {{ python_deploy__path_root }}/get-poetry.py -y --no-modify-path \
            --version {{ python_deploy__poetry_version }}'
    register: result
    environment:
      - POETRY_HOME: '{{ python_deploy__poetry_install_path }}'
    changed_when: '"Latest version already installed" not in result.stdout'
    when: python_deploy__poetry_version != 'latest'
